import os
import datetime
from tkinter import *
window = Tk()
window.title("ELECTRICITY BILLIN SYSTEM")
window.geometry('700x500')
'''
'''

def sub():
    no_of_units=int(t1.get())
    consumer_id=int(t0.get())
    print(no_of_units)
    print(consumer_id)
    if(no_of_units<=50):
        electricity_bill=no_of_units*2.0
        print(electricity_bill)
        l10 = Label(window, text=electricity_bill)
        l10.grid(row=8, column=1)
        l10.config(font=('Times new roman', 12))
        l14 = Label(window, text=no_of_units)
        l14.grid(row=11, column=0)
        l14.config(font=('Times new roman', 12))
        l15 = Label(window, text="Rs.2.0")
        l15.grid(row=11, column=1)
        l15.config(font=('Times new roman', 12))
        l16 = Label(window, text=no_of_units*2.0)
        l16.grid(row=11, column=2)
        l16.config(font=('Times new roman', 12))
        
    elif(no_of_units>50 and no_of_units<=200):
        electricity_bill=(50*2.0)+((no_of_units-50)*2.50)
        print(electricity_bill)
        l10 = Label(window, text=electricity_bill)
        l10.grid(row=8, column=1)
        l10.config(font=('Times new roman', 12))
        l14 = Label(window, text="50")
        l14.grid(row=11, column=0)
        l14.config(font=('Times new roman', 12))
        l15 = Label(window, text="Rs.2.0")
        l15.grid(row=11, column=1)
        l15.config(font=('Times new roman', 12))
        l16 = Label(window, text=50*2.0)
        l16.grid(row=11, column=2)
        l16.config(font=('Times new roman', 12))
        
        l17 = Label(window, text=no_of_units-50)
        l17.grid(row=12, column=0)
        l17.config(font=('Times new roman', 12))
        l18 = Label(window, text="Rs.2.50")
        l18.grid(row=12, column=1)
        l18.config(font=('Times new roman', 12))
        l19 = Label(window, text=(no_of_units-50)*2.50)
        l19.grid(row=12, column=2)
        l19.config(font=('Times new roman', 12))
        
    elif(no_of_units>200 and no_of_units<=400):
        electricity_bill=(50*2.0)+(150*2.50)+((no_of_units-200)*3.0)
        print(electricity_bill)
        l10 = Label(window, text=electricity_bill)
        l10.grid(row=8, column=1)
        l10.config(font=('Times new roman', 12))
        l14 = Label(window, text="50")
        l14.grid(row=11, column=0)
        l14.config(font=('Times new roman', 12))
        l15 = Label(window, text="Rs.2.0")
        l15.grid(row=11, column=1)
        l15.config(font=('Times new roman', 12))
        l16 = Label(window, text=50*2.0)
        l16.grid(row=11, column=2)
        l16.config(font=('Times new roman', 12))
        
        l17 = Label(window, text="150")
        l17.grid(row=12, column=0)
        l17.config(font=('Times new roman', 12))
        l18 = Label(window, text="Rs.2.50")
        l18.grid(row=12, column=1)
        l18.config(font=('Times new roman', 12))
        l19 = Label(window, text=150*2.50)
        l19.grid(row=12, column=2)
        l19.config(font=('Times new roman', 12))

        l20 = Label(window, text=no_of_units-200)
        l20.grid(row=13, column=0)
        l20.config(font=('Times new roman', 12))
        l21 = Label(window, text="Rs.3.0")
        l21.grid(row=13, column=1)
        l21.config(font=('Times new roman', 12))
        l22 = Label(window, text=(no_of_units-200)*3.0)
        l22.grid(row=13, column=2)
        l22.config(font=('Times new roman', 12))
        
    elif(no_of_units>400 and no_of_units<=500):
        electricity_bill=(50*2.0)+(150*2.50)+(200*3.0)+((no_of_units-400)*3.50)
        print(electricity_bill)
        l10 = Label(window, text=electricity_bill)
        l10.grid(row=8, column=1)
        l10.config(font=('Times new roman', 12))
        l14 = Label(window, text="50")
        l14.grid(row=11, column=0)
        l14.config(font=('Times new roman', 12))
        l15 = Label(window, text="Rs.2.0")
        l15.grid(row=11, column=1)
        l15.config(font=('Times new roman', 12))
        l16 = Label(window, text=50*2.0)
        l16.grid(row=11, column=2)
        l16.config(font=('Times new roman', 12))
        
        l17 = Label(window, text="150")
        l17.grid(row=12, column=0)
        l17.config(font=('Times new roman', 12))
        l18 = Label(window, text="Rs.2.50")
        l18.grid(row=12, column=1)
        l18.config(font=('Times new roman', 12))
        l19 = Label(window, text=150*2.50)
        l19.grid(row=12, column=2)
        l19.config(font=('Times new roman', 12))

        l20 = Label(window, text="200")
        l20.grid(row=13, column=0)
        l20.config(font=('Times new roman', 12))
        l21 = Label(window, text="Rs.3.0")
        l21.grid(row=13, column=1)
        l21.config(font=('Times new roman', 12))
        l22 = Label(window, text=200*3.0)
        l22.grid(row=13, column=2)
        l22.config(font=('Times new roman', 12))

        l23 = Label(window, text=no_of_units-400)
        l23.grid(row=14, column=0)
        l23.config(font=('Times new roman', 12))
        l24 = Label(window, text="Rs.3.50")
        l24.grid(row=14, column=1)
        l24.config(font=('Times new roman', 12))
        l25 = Label(window, text=(no_of_units-400)*3.50)
        l25.grid(row=14, column=2)
        l25.config(font=('Times new roman', 12))
        
        
    elif(no_of_units>500):
        electricity_bill=(50*2.0)+(150*2.50)+(200*3.0)+(100*3.50)+((no_of_units-500)*4.0)
        print(electricity_bill)
        l10 = Label(window, text=electricity_bill)
        l10.grid(row=8, column=1)
        l10.config(font=('Times new roman', 12))
        l14 = Label(window, text="50")
        l14.grid(row=11, column=0)
        l14.config(font=('Times new roman', 12))
        l15 = Label(window, text="Rs.2.0")
        l15.grid(row=11, column=1)
        l15.config(font=('Times new roman', 12))
        l16 = Label(window, text=50*2.0)
        l16.grid(row=11, column=2)
        l16.config(font=('Times new roman', 12))
        
        l17 = Label(window, text="150")
        l17.grid(row=12, column=0)
        l17.config(font=('Times new roman', 12))
        l18 = Label(window, text="Rs.2.50")
        l18.grid(row=12, column=1)
        l18.config(font=('Times new roman', 12))
        l19 = Label(window, text=150*2.50)
        l19.grid(row=12, column=2)
        l19.config(font=('Times new roman', 12))

        l20 = Label(window, text="200")
        l20.grid(row=13, column=0)
        l20.config(font=('Times new roman', 12))
        l21 = Label(window, text="Rs.3.0")
        l21.grid(row=13, column=1)
        l21.config(font=('Times new roman', 12))
        l22 = Label(window, text=200*3.0)
        l22.grid(row=13, column=2)
        l22.config(font=('Times new roman', 12))

        l23 = Label(window, text="100")
        l23.grid(row=14, column=0)
        l23.config(font=('Times new roman', 12))
        l24 = Label(window, text="Rs.3.50")
        l24.grid(row=14, column=1)
        l24.config(font=('Times new roman', 12))
        l25 = Label(window, text=100*3.50)
        l25.grid(row=14, column=2)
        l25.config(font=('Times new roman', 12))

        l26 = Label(window, text=no_of_units-500)
        l26.grid(row=15, column=0)
        l26.config(font=('Times new roman', 12))
        l27 = Label(window, text="Rs.3.50")
        l27.grid(row=15, column=1)
        l27.config(font=('Times new roman', 12))
        l28 = Label(window, text=(no_of_units-500)*4.0)
        l28.grid(row=15, column=2)
        l28.config(font=('Times new roman', 12))
        
    
    l4 = Label(window, text="Electricity bill details  : ")
    l4.grid(row=5, column=0)
    l4.config(font=('Times new roman', 12))

    l5 = Label(window, text="Consummer Id.  : ")
    l5.grid(row=6, column=0)
    l5.config(font=('Times new roman', 12))
    
    l6 = Label(window, text=t0.get())
    l6.grid(row=6, column=1)
    l6.config(font=('Times new roman', 12))

    l7 = Label(window, text="Units Consumed : ")
    l7.grid(row=7, column=0)
    l7.config(font=('Times new roman', 12))

    l8 = Label(window, text=no_of_units)
    l8.grid(row=7, column=1)
    l8.config(font=('Times new roman', 12))

    l9 = Label(window, text="Total Amount : ")
    l9.grid(row=8, column=0)
    l9.config(font=('Times new roman', 12))

    l11 = Label(window, text="Bill Breakdown : ")
    l11.grid(row=9, column=0)
    l11.config(font=('Times new roman', 12))

    l11 = Label(window, text="units ")
    l11.grid(row=10, column=0)
    l11.config(font=('Times new roman', 12))
    l12 = Label(window, text="cost/unit")
    l12.grid(row=10, column=1)
    l12.config(font=('Times new roman', 12))
    l13 = Label(window, text="total")
    l13.grid(row=10, column=2)
    l13.config(font=('Times new roman', 12))

    
    def prt():
        print(0)
        f=open("Bills1.rtf",'w+')
        f=open("Bills1.rtf",'a')
        f.write("ABC Electricity Distribution Ltd.")
        f.write("\n")
        f.write(str(datetime.datetime.now()))
        f.write("\n")
        f.write("\n")
        f.write("Consumer ID: ")
        f.write(str(consumer_id))
        f.write("\n")
        f.write("Total Units Consumed: ")
        f.write(str(no_of_units))
        f.write("\n")
        f.write("Total Anount: ")
        f.write(str(electricity_bill))
        f.write("\n")
        f.write("Bill Breakdown: ")
        f.write("\n")
        f.write("Units      ")
        f.write("cost/unit      ")
        f.write("total      ")
        f.write("\n")
        if(no_of_units<=50):
            f.write(str(no_of_units))
            f.write("         ")
            f.write("Rs. 2.0         ")
            f.write(str(2.0*no_of_units))
        elif (no_of_units>50 and no_of_units<=200):
            f.write("50")
            f.write("         ")
            f.write("Rs. 2.0         ")
            f.write(str(2.0*50))
            f.write("\n")
            f.write(str(no_of_units-50))
            f.write("         ")
            f.write("Rs. 2.05         ")
            f.write(str(2.05*(no_of_units-50)))

        elif(no_of_units>200 and no_of_units<=400):
            f.write("50")
            f.write("         ")
            f.write("Rs. 2.0         ")
            f.write(str(2.0*50))
            f.write("\n")
            f.write(str(150))
            f.write("         ")
            f.write("Rs. 2.05         ")
            f.write(str(2.05*150))
            f.write("\n")
            f.write(str(no_of_units-200))
            f.write("         ")
            f.write("Rs. 3.0         ")
            f.write(str(3.0*(no_of_units-200)))

        elif(no_of_units>400 and no_of_units<=500):
            f.write("50")
            f.write("         ")
            f.write("Rs. 2.0         ")
            f.write(str(2.0*50))
            f.write("\n")
            f.write(str(150))
            f.write("         ")
            f.write("Rs. 2.05         ")
            f.write(str(2.05*150))
            f.write("\n")
            f.write(str(200))
            f.write("         ")
            f.write("Rs. 3.0         ")
            f.write(str(3.0*200))
            f.write("\n")
            f.write(str(no_of_units-400))
            f.write("         ")
            f.write("Rs. 3.05         ")
            f.write(str(3.05*(no_of_units-400)))

        elif(no_of_units>500):
            f.write("50")
            f.write("         ")
            f.write("Rs. 2.0         ")
            f.write(str(2.0*50))
            f.write("\n")
            f.write(str(150))
            f.write("         ")
            f.write("Rs. 2.05         ")
            f.write(str(2.05*150))
            f.write("\n")
            f.write(str(200))
            f.write("         ")
            f.write("Rs. 3.0         ")
            f.write(str(3.0*200))
            f.write("\n")
            f.write(str(100))
            f.write("         ")
            f.write("Rs. 3.05         ")
            f.write(str(3.05*100))
            f.write("\n")
            f.write(str(no_of_units-500))
            f.write("         ")
            f.write("Rs. 4.0         ")
            f.write(str(4.0*(no_of_units-500)))

        os.startfile(r'C:\Users\Sankha Subhra Aich\AppData\Local\Programs\Python\Python310\Bills1.rtf')

        
    b2 = Button(window, text="PRINT", command=prt, height = 1, width = 10)
    b2.grid(row=16,column=3)
    

t2=Label(window,text="ABC Electricity Distribution Company Ltd.",justify=CENTER)
t2.grid(row=0, column=0)
t2.config(font=('Times new roman', 12),justify=CENTER)

t3=Label(window,text="-------------------------------------------------------")
t3.grid(row=1, column=0)

l0 = Label(window, text="Enter consumer id  : ")
l0.grid(row=2, column=0)
l0.config(font=('Times new roman', 12),justify='left')

t0 = Entry(window,justify=CENTER, width=20)
t0.grid(row=2,column=1)

ll = Label(window, text="Enter the number of units consumed  : ")
ll.grid(row=3, column=0)
ll.config(font=('Times new roman', 12),justify='left')

t1 = Entry(window,justify=CENTER, width=20)
t1.grid(row=3,column=1)

    
b1 = Button(window, text="SUBMIT", command=sub, height = 1, width = 10)
b1.grid(row=4,column=1)



window.mainloop( )









